name: Weekly Scrape & Upload

on:
  workflow_dispatch:    # manual trigger
  schedule:             # weekly cron
    - cron: '0 2 * * 0' # every Sunday at 02:00 UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chromium & Chromedriver
        run: |
          sudo apt-get update
          # Try installing the modern chromium package; fallback to chromium-browser if needed
          if ! sudo apt-get install -y chromium chromium-chromedriver; then
            sudo apt-get install -y chromium-browser chromium-chromedriver
          fi
          # Create a google-chrome symlink pointing at whichever binary is present
          if [ -x /usr/bin/chromium ]; then
            sudo ln -sf /usr/bin/chromium /usr/bin/google-chrome
          fi
          if [ -x /usr/bin/chromium-browser ]; then
            sudo ln -sf /usr/bin/chromium-browser /usr/bin/google-chrome
          fi

      - name: Run scraper
        working-directory: scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: python scrape_upload.py
