name: Weekly Scrape & Upload

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0'  # every Sunday at 02:00 UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Google Chrome Stable and matching Chromedriver
        run: |
          # 1) Grab Chrome .deb and install
          wget -q -O chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get update
          sudo apt-get install -y ./chrome.deb
          # 2) Determine Chrome major version
          CHROME_VER=$(google-chrome --product-version | cut -d'.' -f1)
          # 3) Fetch matching Chromedriver
          CD_VER=$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VER})
          wget -qO driver.zip https://chromedriver.storage.googleapis.com/${CD_VER}/chromedriver_linux64.zip
          unzip driver.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Run scraper
        working-directory: scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          python scrape_upload.py
