name: Weekly Scrape & Upload

on:
  # Manual trigger
  workflow_dispatch:
  # Weekly schedule: every Sunday at 02:00 UTC (→ 10 PM Saturday ET)
  schedule:
    - cron: '0 2 * * 0'

jobs:
  scrape-and-refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chromium & Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Install PostgreSQL client
        run: sudo apt-get install -y postgresql-client

      - name: Clear all “2” tables
        env:
          PGPASSWORD: ${{ secrets.DB_PASS }}
        run: |
          psql \
            -h ${{ secrets.DB_HOST }} \
            -U ${{ secrets.DB_USER }} \
            -d ${{ secrets.DB_NAME }} \
            -f sql/clear_appended_tables.sql

      # - name: Run scraper
      #   working-directory: scraper
      #   env:
      #     SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      #     SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      #   run: python scrape_upload.py

      - name: Rebuild free-slots (and other) tables
        env:
          PGPASSWORD: ${{ secrets.DB_PASS }}
        run: |
          psql \
            -h ${{ secrets.DB_HOST }} \
            -U ${{ secrets.DB_USER }} \
            -d ${{ secrets.DB_NAME }} \
            -f sql/update_free_slots.sql
